import { Bank } from "@/src/types";

export const NIGERIAN_BANKS: Bank[] = [
  {
    id: 1,
    slug: "9_payment_solutions_bank",
    name: "9 PAYMENT SOLUTIONS BANK",
    code: "120001",
  },
  {
    id: 2,
    slug: "aaa_finance",
    name: "AAA FINANCE",
    code: "050005",
  },
  {
    id: 3,
    slug: "ab_microfinance_bank",
    name: "AB MICROFINANCE BANK ",
    code: "090270",
  },
  {
    id: 4,
    slug: "abbey_mortgage_bank",
    name: "ABBEY MORTGAGE BANK",
    code: "070010",
  },
  {
    id: 5,
    slug: "above_only_microfinance_bank",
    name: "ABOVE ONLY MICROFINANCE BANK ",
    code: "090260",
  },
  {
    id: 6,
    slug: "abu_microfinance_bank",
    name: "ABU MICROFINANCE BANK ",
    code: "090197",
  },
  {
    id: 7,
    slug: "abucoop_microfinance_bank",
    name: "ABUCOOP  MICROFINANCE BANK",
    code: "090424",
  },
  {
    id: 8,
    slug: "accelerex_network_limited",
    name: "ACCELEREX NETWORK LIMITED",
    code: "090202",
  },
  {
    id: 9,
    slug: "access_bank",
    name: "ACCESS BANK",
    code: "000014",
  },
  {
    id: 10,
    slug: "access_money",
    name: "ACCESS MONEY",
    code: "100013",
  },
  {
    id: 11,
    slug: "access_yello_beta",
    name: "ACCESS YELLO & BETA",
    code: "100052",
  },
  {
    id: 12,
    slug: "access_diamond_bank",
    name: "ACCESS(DIAMOND) BANK",
    code: "000005",
  },
  {
    id: 13,
    slug: "accion_microfinance_bank",
    name: "ACCION MICROFINANCE BANK",
    code: "090134",
  },
  {
    id: 14,
    slug: "addosser_microfinance_bank",
    name: "ADDOSSER MICROFINANCE BANK",
    code: "090160",
  },
  {
    id: 15,
    slug: "adeyemi_college_staff_microfinance_bank",
    name: "ADEYEMI COLLEGE STAFF MICROFINANCE BANK",
    code: "090268",
  },
  {
    id: 16,
    slug: "advans_la_fayette_microfinance_bank",
    name: "ADVANS LA FAYETTE  MICROFINANCE BANK",
    code: "090155",
  },
  {
    id: 17,
    slug: "aella_mfb",
    name: "AELLA MFB",
    code: "090614",
  },
  {
    id: 18,
    slug: "afekhafe_microfinance_bank",
    name: "AFEKHAFE MICROFINANCE BANK",
    code: "090292",
  },
  {
    id: 19,
    slug: "ag_mortgage_bank",
    name: "AG MORTGAGE BANK",
    code: "100028",
  },
  {
    id: 20,
    slug: "agosasa_microfinance_bank",
    name: "AGOSASA MICROFINANCE BANK",
    code: "090371",
  },
  {
    id: 21,
    slug: "akalabo_microfinance_bank",
    name: "AKALABO MICROFINANCE BANK ",
    code: "090698",
  },
  {
    id: 22,
    slug: "akwa_savings_loans_limited",
    name: "AKWA SAVINGS & LOANS LIMITED",
    code: "070025",
  },
  {
    id: 23,
    slug: "al_barakah_microfinance_bank",
    name: "AL-BARAKAH MICROFINANCE BANK",
    code: "090133",
  },
  {
    id: 24,
    slug: "al_hayat_microfinance_bank",
    name: "AL-HAYAT MICROFINANCE BANK",
    code: "090277",
  },
  {
    id: 25,
    slug: "alekun_microfinance_bank",
    name: "ALEKUN MICROFINANCE BANK",
    code: "090259",
  },
  {
    id: 26,
    slug: "alert_microfinance_bank",
    name: "ALERT MICROFINANCE BANK",
    code: "090297",
  },
  {
    id: 27,
    slug: "allworkers_microfinance_bank",
    name: "ALLWORKERS MICROFINANCE BANK",
    code: "090131",
  },
  {
    id: 28,
    slug: "alpha_kapital_microfinance_bank",
    name: "ALPHA KAPITAL MICROFINANCE BANK ",
    code: "090169",
  },
  {
    id: 29,
    slug: "alternative_bank_limited",
    name: "ALTERNATIVE BANK LIMITED",
    code: "000037",
  },
  {
    id: 30,
    slug: "amac_microfinance_bank",
    name: "AMAC MICROFINANCE BANK",
    code: "090394",
  },
  {
    id: 31,
    slug: "amju_unique_microfinance_bank",
    name: "AMJU UNIQUE MICROFINANCE BANK",
    code: "090180",
  },
  {
    id: 32,
    slug: "amml_microfinance_bank",
    name: "AMML MICROFINANCE BANK ",
    code: "090116",
  },
  {
    id: 33,
    slug: "amoye_microfinance_bank",
    name: "AMOYE MICROFINANCE BANK",
    code: "090610",
  },
  {
    id: 34,
    slug: "apeks_microfinance_bank",
    name: "APEKS MICROFINANCE BANK",
    code: "090143",
  },
  {
    id: 35,
    slug: "apple_microfinance_bank",
    name: "APPLE MICROFINANCE BANK",
    code: "090376",
  },
  {
    id: 36,
    slug: "aramoko_microfinance_bank",
    name: "ARAMOKO MICROFINANCE BANK",
    code: "090307",
  },
  {
    id: 37,
    slug: "arise_microfinance_bank",
    name: "ARISE MICROFINANCE BANK",
    code: "090282",
  },
  {
    id: 38,
    slug: "aso_savings",
    name: "ASO SAVINGS",
    code: "090001",
  },
  {
    id: 39,
    slug: "assetmatrix_microfinance_bank",
    name: "ASSETMATRIX MICROFINANCE BANK",
    code: "090287",
  },
  {
    id: 40,
    slug: "astrapolaris_microfinance_bank",
    name: "ASTRAPOLARIS MICROFINANCE BANK",
    code: "090172",
  },
  {
    id: 41,
    slug: "atbu_microfinance_bank",
    name: "ATBU  Microfinance Bank",
    code: "090451",
  },
  {
    id: 42,
    slug: "auchi_microfinance_bank",
    name: "AUCHI MICROFINANCE BANK ",
    code: "090264",
  },
  {
    id: 43,
    slug: "ave_maria_microfinance_bank_ltd",
    name: "AVE MARIA MICROFINANCE BANK LTD",
    code: "090600",
  },
  {
    id: 44,
    slug: "abulesoro_microfinance_bank_ltd",
    name: "Abulesoro Microfinance Bank Ltd",
    code: "090545",
  },
  {
    id: 45,
    slug: "ada_microfinance_bank",
    name: "Ada Microfinance Bank",
    code: "090483",
  },
  {
    id: 46,
    slug: "afemai_microfinance_bank",
    name: "Afemai Microfinance Bank",
    code: "090518",
  },
  {
    id: 47,
    slug: "akpo_microfinance_bank",
    name: "Akpo Microfinance Bank",
    code: "090608",
  },
  {
    id: 48,
    slug: "aku_microfinance_bank",
    name: "Aku Microfinance Bank",
    code: "090531",
  },
  {
    id: 49,
    slug: "akuchukwu_microfinance_bank_ltd",
    name: "Akuchukwu Microfinance Bank Ltd",
    code: "090561",
  },
  {
    id: 50,
    slug: "ally_microfinance_bank",
    name: "Ally Microfinance Bank",
    code: "090548",
  },
  {
    id: 51,
    slug: "alvana_microfinance_bank",
    name: "Alvana Microfinance Bank",
    code: "090489",
  },
  {
    id: 52,
    slug: "anchorage_microfinance_bank",
    name: "Anchorage Microfinance Bank",
    code: "090476",
  },
  {
    id: 53,
    slug: "aniocha_microfinance_bank",
    name: "Aniocha Microfinance Bank",
    code: "090469",
  },
  {
    id: 54,
    slug: "aspire_microfinance_bank_ltd",
    name: "Aspire Microfinance Bank Ltd",
    code: "090544",
  },
  {
    id: 55,
    slug: "assets_microfinance_bank",
    name: "Assets Microfinance Bank",
    code: "090473",
  },
  {
    id: 56,
    slug: "avuenegbe_microfinance_bank",
    name: "Avuenegbe Microfinance Bank",
    code: "090478",
  },
  {
    id: 57,
    slug: "aztec_microfinance_bank",
    name: "Aztec Microfinance Bank",
    code: "090540",
  },
  {
    id: 58,
    slug: "baines_credit_microfinance_bank",
    name: "BAINES CREDIT MICROFINANCE BANK",
    code: "090188",
  },
  {
    id: 59,
    slug: "balogun_fulani_microfinance_bank",
    name: "BALOGUN FULANI  MICROFINANCE BANK",
    code: "090181",
  },
  {
    id: 60,
    slug: "balogun_gambari_microfinance_bank",
    name: "BALOGUN GAMBARI MICROFINANCE BANK",
    code: "090326",
  },
  {
    id: 61,
    slug: "banc_corp_microfinance_bank",
    name: "BANC CORP MICROFINANCE BANK",
    code: "090581",
  },
  {
    id: 62,
    slug: "banex_microfinance_bank",
    name: "BANEX MICROFINANCE BANK",
    code: "090425",
  },
  {
    id: 63,
    slug: "bayero_university_microfinance_bank",
    name: "BAYERO UNIVERSITY MICROFINANCE BANK",
    code: "090316",
  },
  {
    id: 64,
    slug: "bc_kash_microfinance_bank",
    name: "BC KASH MICROFINANCE BANK",
    code: "090127",
  },
  {
    id: 65,
    slug: "bellabank_microfinance_bank",
    name: "BELLABANK MICROFINANCE BANK",
    code: "090672",
  },
  {
    id: 66,
    slug: "benysta_microfinance_bank",
    name: "BENYSTA MICROFINANCE BANK",
    code: "090413",
  },
  {
    id: 67,
    slug: "bipc_microfinance_bank",
    name: "BIPC MICROFINANCE BANK",
    code: "090336",
  },
  {
    id: 68,
    slug: "bluewhales_microfinance_bank",
    name: "BLUEWHALES  MICROFINANCE BANK",
    code: "090431",
  },
  {
    id: 69,
    slug: "boctrust_microfinance_bank_limited",
    name: "BOCTRUST MICROFINANCE BANK LIMITED",
    code: "090117",
  },
  {
    id: 70,
    slug: "boi_mf_bank",
    name: "BOI MF BANK",
    code: "090444",
  },
  {
    id: 71,
    slug: "bonghe_microfinance_bank",
    name: "BONGHE MICROFINANCE BANK",
    code: "090319",
  },
  {
    id: 72,
    slug: "borgu_microfinance_bank",
    name: "BORGU  MICROFINANCE BANK",
    code: "090395",
  },
  {
    id: 73,
    slug: "bosak_microfinance_bank",
    name: "BOSAK MICROFINANCE BANK",
    code: "090176",
  },
  {
    id: 74,
    slug: "bowen_microfinance_bank",
    name: "BOWEN MICROFINANCE BANK",
    code: "090148",
  },
  {
    id: 75,
    slug: "brent_mortgage_bank",
    name: "BRENT MORTGAGE BANK",
    code: "070015",
  },
  {
    id: 76,
    slug: "brethren_microfinance_bank",
    name: "BRETHREN MICROFINANCE BANK",
    code: "090293",
  },
  {
    id: 77,
    slug: "bridgeway_microfinanace_bank",
    name: "BRIDGEWAY MICROFINANACE BANK",
    code: "090393",
  },
  {
    id: 78,
    slug: "brightway_microfinance_bank",
    name: "BRIGHTWAY MICROFINANCE BANK",
    code: "090308",
  },
  {
    id: 79,
    slug: "business_support_microfinance_bank",
    name: "BUSINESS SUPPORT MICROFINANCE BANK",
    code: "090406",
  },
  {
    id: 80,
    slug: "balera_microfinance_bank_ltd",
    name: "Balera Microfinance Bank Ltd",
    code: "090563",
  },
  {
    id: 81,
    slug: "bankly_microfinance_bank",
    name: "Bankly Microfinance Bank",
    code: "090529",
  },
  {
    id: 82,
    slug: "beststar_microfinance_bank",
    name: "Beststar Microfinance Bank",
    code: "090615",
  },
  {
    id: 83,
    slug: "bishopgate_microfinance_bank",
    name: "Bishopgate Microfinance Bank",
    code: "090555",
  },
  {
    id: 84,
    slug: "blue_investments_microfinance_bank",
    name: "Blue Investments Microfinance Bank",
    code: "090538",
  },
  {
    id: 85,
    slug: "boji_boji_microfinance_bank",
    name: "Boji Boji Microfinance Bank",
    code: "090494",
  },
  {
    id: 86,
    slug: "bokkos_mfb",
    name: "Bokkos MFB",
    code: "090703",
  },
  {
    id: 87,
    slug: "borno_renaissance_microfinance_bank",
    name: "Borno Renaissance Microfinance Bank",
    code: "090508",
  },
  {
    id: 88,
    slug: "boromu_microfinance_bank",
    name: "Boromu Microfinance Bank",
    code: "090501",
  },
  {
    id: 89,
    slug: "borstal_microfinance_bank",
    name: "Borstal Microfinance Bank",
    code: "090454",
  },
  {
    id: 90,
    slug: "branch_international_finance_company_limited",
    name: "Branch International Finance Company Limited",
    code: "050006",
  },
  {
    id: 91,
    slug: "broadview_microfinance_bank_ltd",
    name: "Broadview Microfinance Bank Ltd",
    code: "090568",
  },
  {
    id: 92,
    slug: "bubayero_microfinance_bank",
    name: "Bubayero Microfinance Bank",
    code: "090512",
  },
  {
    id: 93,
    slug: "calabar_microfinance_bank",
    name: "CALABAR MICROFINANCE BANK",
    code: "090415",
  },
  {
    id: 94,
    slug: "capstone_microfinance_bank",
    name: "CAPSTONE MICROFINANCE BANK ",
    code: "090445",
  },
  {
    id: 95,
    slug: "carbon",
    name: "CARBON",
    code: "100026",
  },
  {
    id: 96,
    slug: "cashconnect_microfinance_bank",
    name: "CASHCONNECT MICROFINANCE BANK",
    code: "090360",
  },
  {
    id: 97,
    slug: "cashrite_microfinance_bank",
    name: "CASHRITE MICROFINANCE BANK",
    code: "090649",
  },
  {
    id: 98,
    slug: "cbn",
    name: "CBN",
    code: "000028",
  },
  {
    id: 99,
    slug: "cbn_tsa",
    name: "CBN_TSA",
    code: "999001",
  },
  {
    id: 100,
    slug: "cellulant",
    name: "CELLULANT",
    code: "100005",
  },
  {
    id: 101,
    slug: "cemcs_microfinance_bank",
    name: "CEMCS MICROFINANCE BANK",
    code: "090154",
  },
  {
    id: 102,
    slug: "chanelle_bank",
    name: "CHANELLE BANK",
    code: "090397",
  },
  {
    id: 103,
    slug: "cherish_microfinance_bank",
    name: "CHERISH MICROFINANCE BANK",
    code: "090440",
  },
  {
    id: 104,
    slug: "chibueze_microfinance_bank",
    name: "CHIBUEZE MICROFINANCE BANK",
    code: "090416",
  },
  {
    id: 105,
    slug: "chikum_microfinance_bank",
    name: "CHIKUM MICROFINANCE BANK",
    code: "090141",
  },
  {
    id: 106,
    slug: "cit_microfinance_bank",
    name: "CIT MICROFINANCE BANK",
    code: "090144",
  },
  {
    id: 107,
    slug: "citi_bank",
    name: "CITI BANK",
    code: "000009",
  },
  {
    id: 108,
    slug: "citizen_trust_microfinance_bank_ltd",
    name: "CITIZEN TRUST MICROFINANCE BANK LTD",
    code: "090343",
  },
  {
    id: 109,
    slug: "clearpay_microfinance_bank",
    name: "CLEARPAY MICROFINANCE BANK",
    code: "090482",
  },
  {
    id: 110,
    slug: "coalcamp_microfinance_bank",
    name: "COALCAMP MICROFINANCE BANK",
    code: "090254",
  },
  {
    id: 111,
    slug: "coastline_microfinance_bank",
    name: "COASTLINE MICROFINANCE BANK",
    code: "090374",
  },
  {
    id: 112,
    slug: "consumer_microfinance_bank",
    name: "CONSUMER MICROFINANCE BANK",
    code: "090130",
  },
  {
    id: 113,
    slug: "coop_mortgage_bank",
    name: "COOP MORTGAGE BANK",
    code: "070021",
  },
  {
    id: 114,
    slug: "corestep_microfinance_bank",
    name: "CORESTEP MICROFINANCE BANK",
    code: "090365",
  },
  {
    id: 115,
    slug: "coronation_merchant_bank",
    name: "CORONATION MERCHANT BANK",
    code: "060001",
  },
  {
    id: 116,
    slug: "county_finance_ltd",
    name: "COUNTY FINANCE LTD",
    code: "050001",
  },
  {
    id: 117,
    slug: "covenant_microfinance_bank",
    name: "COVENANT MICROFINANCE BANK",
    code: "070006",
  },
  {
    id: 118,
    slug: "credit_afrique_microfinance_bank",
    name: "CREDIT AFRIQUE MICROFINANCE BANK",
    code: "090159",
  },
  {
    id: 119,
    slug: "crossriver_microfinance_bank",
    name: "CROSSRIVER  MICROFINANCE BANK",
    code: "090429",
  },
  {
    id: 120,
    slug: "crutech_microfinance_bank",
    name: "CRUTECH  MICROFINANCE BANK",
    code: "090414",
  },
  {
    id: 121,
    slug: "capitalmetriq_swift_microfinance_bank",
    name: "Capitalmetriq Swift Microfinance Bank",
    code: "090509",
  },
  {
    id: 122,
    slug: "caretaker_microfinance_bank",
    name: "Caretaker Microfinance Bank",
    code: "090472",
  },
  {
    id: 123,
    slug: "catland_microfinance_bank",
    name: "Catland Microfinance Bank",
    code: "090498",
  },
  {
    id: 124,
    slug: "cedar_microfinance_bank_ltd",
    name: "Cedar Microfinance Bank Ltd",
    code: "090562",
  },
  {
    id: 125,
    slug: "chase_microfinance_bank",
    name: "Chase Microfinance Bank",
    code: "090523",
  },
  {
    id: 126,
    slug: "chukwunenye_microfinance_bank",
    name: "Chukwunenye  Microfinance Bank",
    code: "090490",
  },
  {
    id: 127,
    slug: "cloverleaf_microfinance_bank",
    name: "Cloverleaf  Microfinance Bank",
    code: "090511",
  },
  {
    id: 128,
    slug: "confidence_microfinance_bank_ltd",
    name: "Confidence Microfinance Bank Ltd",
    code: "090530",
  },
  {
    id: 129,
    slug: "consistent_trust_microfinance_bank_ltd",
    name: "Consistent Trust Microfinance Bank Ltd",
    code: "090553",
  },
  {
    id: 130,
    slug: "creditville_microfinance_bank",
    name: "Creditville Microfinance Bank",
    code: "090611",
  },
  {
    id: 131,
    slug: "crescent_microfinance_bank",
    name: "Crescent Microfinance Bank",
    code: "090526",
  },
  {
    id: 132,
    slug: "dal_microfinance_bank",
    name: "DAL MICROFINANCE BANK ",
    code: "090596",
  },
  {
    id: 133,
    slug: "davodani_microfinance_bank",
    name: "DAVODANI  MICROFINANCE BANK",
    code: "090391",
  },
  {
    id: 134,
    slug: "daylight_microfinance_bank",
    name: "DAYLIGHT MICROFINANCE BANK",
    code: "090167",
  },
  {
    id: 135,
    slug: "delta_trust_mortgage_bank",
    name: "DELTA TRUST MORTGAGE BANK",
    code: "070023",
  },
  {
    id: 136,
    slug: "dignity_finance",
    name: "DIGNITY FINANCE",
    code: "050013",
  },
  {
    id: 137,
    slug: "dot_microfinance_bank",
    name: "DOT MICROFINANCE BANK",
    code: "090470",
  },
  {
    id: 138,
    slug: "e_barcs_microfinance_bank",
    name: "E-BARCS MICROFINANCE BANK",
    code: "090156",
  },
  {
    id: 139,
    slug: "eagle_flight_microfinance_bank",
    name: "EAGLE FLIGHT MICROFINANCE BANK",
    code: "090294",
  },
  {
    id: 140,
    slug: "eartholeum",
    name: "EARTHOLEUM",
    code: "100021",
  },
  {
    id: 141,
    slug: "ebsu_microfinance_bank",
    name: "EBSU MICROFINANCE BANK",
    code: "090427",
  },
  {
    id: 142,
    slug: "ecobank",
    name: "ECOBANK",
    code: "000010",
  },
  {
    id: 143,
    slug: "ecobank_xpress_account",
    name: "ECOBANK XPRESS ACCOUNT",
    code: "100008",
  },
  {
    id: 144,
    slug: "ecomobile",
    name: "ECOMOBILE",
    code: "100030",
  },
  {
    id: 145,
    slug: "edfin_microfinance_bank",
    name: "EDFIN MICROFINANCE BANK",
    code: "090310",
  },
  {
    id: 146,
    slug: "ek_reliable_microfinance_bank",
    name: "EK-RELIABLE MICROFINANCE BANK",
    code: "090389",
  },
  {
    id: 147,
    slug: "ekondo_microfinance_bank",
    name: "EKONDO MICROFINANCE BANK",
    code: "090097",
  },
  {
    id: 148,
    slug: "emaar_microfinance_bank",
    name: "EMAAR MICROFINANCE BANK",
    code: "090712",
  },
  {
    id: 149,
    slug: "emerald_microfinance_bank",
    name: "EMERALD MICROFINANCE BANK",
    code: "090273",
  },
  {
    id: 150,
    slug: "empire_trust_microfinance_bank",
    name: "EMPIRE TRUST MICROFINANCE BANK",
    code: "090114",
  },
  {
    id: 151,
    slug: "enaira",
    name: "ENAIRA",
    code: "000033",
  },
  {
    id: 152,
    slug: "enco_finance",
    name: "ENCO FINANCE",
    code: "050012",
  },
  {
    id: 153,
    slug: "enterprise_bank",
    name: "ENTERPRISE BANK",
    code: "000019",
  },
  {
    id: 154,
    slug: "esan_microfinance_bank",
    name: "ESAN MICROFINANCE BANK",
    code: "090189",
  },
  {
    id: 155,
    slug: "eso_e_microfinance_bank",
    name: "ESO-E MICROFINANCE BANK",
    code: "090166",
  },
  {
    id: 156,
    slug: "etranzact",
    name: "ETRANZACT",
    code: "100006",
  },
  {
    id: 157,
    slug: "evangel_microfinance_bank",
    name: "EVANGEL MICROFINANCE BANK ",
    code: "090304",
  },
  {
    id: 158,
    slug: "evergreen_microfinance_bank",
    name: "EVERGREEN MICROFINANCE BANK",
    code: "090332",
  },
  {
    id: 159,
    slug: "eyowo",
    name: "EYOWO",
    code: "090328",
  },
  {
    id: 160,
    slug: "egwafin_microfinance_bank_ltd",
    name: "Egwafin Microfinance Bank Ltd",
    code: "090556",
  },
  {
    id: 161,
    slug: "ekimogun_microfinance_bank",
    name: "Ekimogun Microfinance Bank",
    code: "090552",
  },
  {
    id: 162,
    slug: "enrich_microfinance_bank",
    name: "Enrich Microfinance Bank",
    code: "090539",
  },
  {
    id: 163,
    slug: "ewt_microfinance_bank",
    name: "Ewt Microfinance Bank",
    code: "090572",
  },
  {
    id: 164,
    slug: "excellent_microfinance_bank",
    name: "Excellent Microfinance Bank",
    code: "090541",
  },
  {
    id: 165,
    slug: "fame_microfinance_bank",
    name: "FAME MICROFINANCE BANK",
    code: "090330",
  },
  {
    id: 166,
    slug: "fast_credit",
    name: "FAST CREDIT",
    code: "050009",
  },
  {
    id: 167,
    slug: "fast_microfinance_bank",
    name: "FAST MICROFINANCE BANK",
    code: "090179",
  },
  {
    id: 168,
    slug: "fbnquest_merchant_bank",
    name: "FBNQUEST MERCHANT BANK",
    code: "060002",
  },
  {
    id: 169,
    slug: "fcmb_microfinance_bank",
    name: "FCMB MICROFINANCE BANK",
    code: "090409",
  },
  {
    id: 170,
    slug: "fcmb_mobile",
    name: "FCMB MOBILE",
    code: "100031",
  },
  {
    id: 171,
    slug: "fct_microfinance_bank",
    name: "FCT MICROFINANCE BANK",
    code: "090290",
  },
  {
    id: 172,
    slug: "federal_polytechnic_nekede_microfinance_bank",
    name: "FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK",
    code: "090398",
  },
  {
    id: 173,
    slug: "federal_university_dutse_microfinance_bank",
    name: "FEDERAL UNIVERSITY DUTSE MICROFINANCE BANK",
    code: "090318",
  },
  {
    id: 174,
    slug: "fedpoly_nasarawa_microfinance_bank",
    name: "FEDPOLY NASARAWA MICROFINANCE BANK",
    code: "090298",
  },
  {
    id: 175,
    slug: "fets",
    name: "FETS",
    code: "100001",
  },
  {
    id: 176,
    slug: "fewchore_finance_company_limited",
    name: "FEWCHORE FINANCE COMPANY LIMITED",
    code: "050002",
  },
  {
    id: 177,
    slug: "ffs_microfinance_bank",
    name: "FFS MICROFINANCE BANK",
    code: "090153",
  },
  {
    id: 178,
    slug: "fha_mortgage_bank_ltd",
    name: "FHA MORTGAGE BANK LTD",
    code: "070026",
  },
  {
    id: 179,
    slug: "fidelity_bank",
    name: "FIDELITY BANK",
    code: "000007",
  },
  {
    id: 180,
    slug: "fidelity_mobile",
    name: "FIDELITY MOBILE",
    code: "100019",
  },
  {
    id: 181,
    slug: "fidfund_microfinance_bank",
    name: "FIDFUND MICROFINANCE BANK",
    code: "090126",
  },
  {
    id: 182,
    slug: "finatrust_microfinance_bank",
    name: "FINATRUST MICROFINANCE BANK",
    code: "090111",
  },
  {
    id: 183,
    slug: "finca_microfinance_bank",
    name: "FINCA MICROFINANCE BANK",
    code: "090400",
  },
  {
    id: 184,
    slug: "firmus_microfinance_bank",
    name: "FIRMUS MICROFINANCE BANK",
    code: "090366",
  },
  {
    id: 185,
    slug: "first_bank_of_nigeria",
    name: "FIRST BANK OF NIGERIA",
    code: "000016",
  },
  {
    id: 186,
    slug: "first_city_monument_bank",
    name: "FIRST CITY MONUMENT BANK",
    code: "000003",
  },
  {
    id: 187,
    slug: "first_generation_mortgage_bank",
    name: "FIRST GENERATION MORTGAGE BANK",
    code: "070014",
  },
  {
    id: 188,
    slug: "first_multiple_microfinance_bank",
    name: "FIRST MULTIPLE MICROFINANCE BANK",
    code: "090163",
  },
  {
    id: 189,
    slug: "first_option_microfinance_bank",
    name: "FIRST OPTION MICROFINANCE BANK",
    code: "090285",
  },
  {
    id: 190,
    slug: "first_royal_microfinance_bank",
    name: "FIRST ROYAL MICROFINANCE BANK",
    code: "090164",
  },
  {
    id: 191,
    slug: "first_trust_mortgage_bank_plc",
    name: "FIRST TRUST MORTGAGE BANK PLC",
    code: "090107",
  },
  {
    id: 192,
    slug: "firstmonie_wallet",
    name: "FIRSTMONIE WALLET",
    code: "100014",
  },
  {
    id: 193,
    slug: "focus_mfb",
    name: "FOCUS MFB",
    code: "090709",
  },
  {
    id: 194,
    slug: "fortis_microfinance_bank",
    name: "FORTIS MICROFINANCE BANK",
    code: "070002",
  },
  {
    id: 195,
    slug: "fortis_mobile",
    name: "FORTIS MOBILE",
    code: "100016",
  },
  {
    id: 196,
    slug: "fsdh",
    name: "FSDH",
    code: "400001",
  },
  {
    id: 197,
    slug: "fullrange_microfinance_bank",
    name: "FULLRANGE MICROFINANCE BANK",
    code: "090145",
  },
  {
    id: 198,
    slug: "fundquest_financial_services_ltd",
    name: "FUNDQUEST FINANCIAL SERVICES LTD",
    code: "050010",
  },
  {
    id: 199,
    slug: "futminna_microfinance_bank",
    name: "FUTMINNA MICROFINANCE BANK",
    code: "090438",
  },
  {
    id: 200,
    slug: "futo_microfinance_bank",
    name: "FUTO MICROFINANCE BANK",
    code: "090158",
  },
  {
    id: 201,
    slug: "fairmoney_microfinance_bank_ltd",
    name: "Fairmoney Microfinance Bank Ltd",
    code: "090551",
  },
  {
    id: 202,
    slug: "fims_microfinance_bank",
    name: "Fims Microfinance Bank",
    code: "090507",
  },
  {
    id: 203,
    slug: "first_heritage_microfinance_bank",
    name: "First Heritage Microfinance Bank",
    code: "090479",
  },
  {
    id: 204,
    slug: "firstmidas_microfinance_bank_ltd",
    name: "Firstmidas Microfinance Bank Ltd",
    code: "090575",
  },
  {
    id: 205,
    slug: "foresight_microfinance_bank",
    name: "Foresight Microfinance Bank",
    code: "090521",
  },
  {
    id: 206,
    slug: "fortress_microfinance_bank",
    name: "Fortress Microfinance Bank",
    code: "090486",
  },
  {
    id: 207,
    slug: "gashua_microfinance_bank",
    name: "GASHUA MICROFINANCE BANK",
    code: "090168",
  },
  {
    id: 208,
    slug: "gateway_mortgage_bank",
    name: "GATEWAY MORTGAGE BANK",
    code: "070009",
  },
  {
    id: 209,
    slug: "gidauniyar_alheri_microfinance_bank",
    name: "GIDAUNIYAR ALHERI MICROFINANCE BANK",
    code: "090621",
  },
  {
    id: 210,
    slug: "giginya_microfinance_bank",
    name: "GIGINYA MICROFINANCE BANK",
    code: "090411",
  },
  {
    id: 211,
    slug: "girei_microfinanace_bank",
    name: "GIREI MICROFINANACE BANK",
    code: "090186",
  },
  {
    id: 212,
    slug: "giwa_microfinance_bank",
    name: "GIWA MICROFINANCE BANK",
    code: "090441",
  },
  {
    id: 213,
    slug: "globus_bank",
    name: "GLOBUS BANK",
    code: "000027",
  },
  {
    id: 214,
    slug: "glory_microfinance_bank",
    name: "GLORY MICROFINANCE BANK",
    code: "090278",
  },
  {
    id: 215,
    slug: "gmb_microfinance_bank",
    name: "GMB MICROFINANCE BANK",
    code: "090408",
  },
  {
    id: 216,
    slug: "goldman_microfinance_bank",
    name: "GOLDMAN MICROFINANCE BANK",
    code: "090574",
  },
  {
    id: 217,
    slug: "gombe_microfinance_bank_ltd",
    name: "GOMBE MICROFINANCE BANK LTD",
    code: "090586",
  },
  {
    id: 218,
    slug: "gowans_microfinance_bank",
    name: "GOWANS MICROFINANCE BANK",
    code: "090122",
  },
  {
    id: 219,
    slug: "grant_mf_bank",
    name: "GRANT MF BANK",
    code: "090335",
  },
  {
    id: 220,
    slug: "greenbank_microfinance_bank",
    name: "GREENBANK MICROFINANCE BANK",
    code: "090178",
  },
  {
    id: 221,
    slug: "greenville_microfinance_bank",
    name: "GREENVILLE MICROFINANCE BANK",
    code: "090269",
  },
  {
    id: 222,
    slug: "greenwich_merchant_bank",
    name: "GREENWICH MERCHANT BANK",
    code: "060004",
  },
  {
    id: 223,
    slug: "grooming_microfinance_bank",
    name: "GROOMING MICROFINANCE BANK",
    code: "090195",
  },
  {
    id: 224,
    slug: "gt_mobile",
    name: "GT MOBILE",
    code: "100009",
  },
  {
    id: 225,
    slug: "guarantee_trust_bank",
    name: "GUARANTY TRUST BANK",
    code: "000013",
  },
  {
    id: 226,
    slug: "gti_microfinance_bank",
    name: "GTI MICROFINANCE BANK",
    code: "090385",
  },
  {
    id: 227,
    slug: "gabsyn_microfinance_bank",
    name: "Gabsyn Microfinance Bank",
    code: "090591",
  },
  {
    id: 228,
    slug: "garki_microfinance_bank",
    name: "Garki Microfinance Bank",
    code: "090484",
  },
  {
    id: 229,
    slug: "gbede_microfinance_bank",
    name: "Gbede Microfinance Bank",
    code: "090579",
  },
  {
    id: 230,
    slug: "giant_stride_microfinance_bank",
    name: "Giant Stride Microfinance Bank",
    code: "090475",
  },
  {
    id: 231,
    slug: "good_neighbours_microfinance_bank",
    name: "Good Neighbours Microfinance Bank",
    code: "090467",
  },
  {
    id: 232,
    slug: "green_energy_microfinance_bank_ltd",
    name: "Green Energy Microfinance Bank Ltd",
    code: "090550",
  },
  {
    id: 233,
    slug: "greenacres_mfb",
    name: "Greenacres MFB",
    code: "090599",
  },
  {
    id: 234,
    slug: "gwong_microfinance_bank",
    name: "Gwong Microfinance Bank",
    code: "090500",
  },
  {
    id: 235,
    slug: "hackman_microfinance_bank",
    name: "HACKMAN MICROFINANCE BANK",
    code: "090147",
  },
  {
    id: 236,
    slug: "haggai_mortgage_bank_limited",
    name: "HAGGAI MORTGAGE BANK LIMITED",
    code: "070017",
  },
  {
    id: 237,
    slug: "halacredit_microfinance_bank",
    name: "HALACREDIT MICROFINANCE BANK",
    code: "090291",
  },
  {
    id: 238,
    slug: "hasal_microfinance_bank",
    name: "HASAL MICROFINANCE BANK",
    code: "090121",
  },
  {
    id: 239,
    slug: "headway_microfinance_bank",
    name: "HEADWAY MICROFINANCE BANK",
    code: "090363",
  },
  {
    id: 240,
    slug: "hedonmark",
    name: "HEDONMARK",
    code: "100017",
  },
  {
    id: 241,
    slug: "heritage_bank",
    name: "HERITAGE BANK",
    code: "000020",
  },
  {
    id: 242,
    slug: "highland_microfinance_bank",
    name: "HIGHLAND MICROFINANCE BANK",
    code: "090418",
  },
  {
    id: 243,
    slug: "homebase_mortgage_bank",
    name: "HOMEBASE MORTGAGE BANK",
    code: "070024",
  },
  {
    id: 244,
    slug: "hopepsb",
    name: "HOPEPSB",
    code: "120002",
  },
  {
    id: 245,
    slug: "iba_mfb",
    name: "IBA MFB ",
    code: "090598",
  },
  {
    id: 246,
    slug: "ibank_microfinance_bank",
    name: "IBANK MICROFINANCE BANK",
    code: "090115",
  },
  {
    id: 247,
    slug: "ibeto_microfinance_bank",
    name: "IBETO  MICROFINANCE BANK",
    code: "090439",
  },
  {
    id: 248,
    slug: "ibile_microfinance_bank",
    name: "IBILE MICROFINANCE BANK",
    code: "090118",
  },
  {
    id: 249,
    slug: "ic_globalmicrofinance_bank",
    name: "IC Globalmicrofinance Bank",
    code: "090520",
  },
  {
    id: 250,
    slug: "ihala_microfinance_bank",
    name: "IHALA MICROFINANCE BANK",
    code: "090725",
  },
  {
    id: 251,
    slug: "ikenne_microfinance_bank",
    name: "IKENNE MICROFINANCE BANK",
    code: "090324",
  },
  {
    id: 252,
    slug: "ikire_microfinance_bank",
    name: "IKIRE MICROFINANCE BANK",
    code: "090279",
  },
  {
    id: 253,
    slug: "ile_oluji_microfinance_bank",
    name: "ILE-OLUJI MICROFINANCE BANK",
    code: "090710",
  },
  {
    id: 254,
    slug: "ilisan_microfinance_bank",
    name: "ILISAN MICROFINANCE BANK",
    code: "090370",
  },
  {
    id: 255,
    slug: "illorin_microfinance_bank",
    name: "ILLORIN MICROFINANCE BANK",
    code: "090350",
  },
  {
    id: 256,
    slug: "ilora_microfinance_bank",
    name: "ILORA MICROFINANCE BANK",
    code: "090430",
  },
  {
    id: 257,
    slug: "imo_state_microfinance_bank",
    name: "IMO STATE MICROFINANCE BANK",
    code: "090258",
  },
  {
    id: 258,
    slug: "imowo_microfinance_bank",
    name: "IMOWO MICROFINANCE BANK",
    code: "090417",
  },
  {
    id: 259,
    slug: "imperial_homes_mortgage_bank",
    name: "IMPERIAL HOMES MORTGAGE BANK",
    code: "100024",
  },
  {
    id: 260,
    slug: "infinity_microfinance_bank",
    name: "INFINITY MICROFINANCE BANK",
    code: "090157",
  },
  {
    id: 261,
    slug: "infinity_trust_mortgage_bank",
    name: "INFINITY TRUST MORTGAGE BANK",
    code: "070016",
  },
  {
    id: 262,
    slug: "innovectives_kesh",
    name: "INNOVECTIVES KESH",
    code: "100029",
  },
  {
    id: 263,
    slug: "insight_microfinance_bank",
    name: "INSIGHT MICROFINANCE BANK",
    code: "090434",
  },
  {
    id: 264,
    slug: "interland_microfinance_bank",
    name: "INTERLAND MICROFINANCE BANK",
    code: "090386",
  },
  {
    id: 265,
    slug: "irl_microfinance_bank",
    name: "IRL MICROFINANCE BANK",
    code: "090149",
  },
  {
    id: 266,
    slug: "isaleoyo_microfinance_bank",
    name: "ISALEOYO MICROFINANCE BANK",
    code: "090377",
  },
  {
    id: 267,
    slug: "ishie_microfinance_bank",
    name: "ISHIE  MICROFINANCE BANK",
    code: "090428",
  },
  {
    id: 268,
    slug: "isua_microfinance_bank",
    name: "ISUA MICROFINANCE BANK ",
    code: "090701",
  },
  {
    id: 269,
    slug: "isuofia_microfinance_bank",
    name: "ISUOFIA MICROFINANCE BANK",
    code: "090353",
  },
  {
    id: 270,
    slug: "itex_integrated_services_limited",
    name: "ITEX INTEGRATED SERVICES LIMITED",
    code: "090211",
  },
  {
    id: 271,
    slug: "iyeru_okin_microfinance_bank_ltd",
    name: "IYERU OKIN MICROFINANCE BANK LTD",
    code: "090337",
  },
  {
    id: 272,
    slug: "izon_microfinance_bank",
    name: "IZON MICROFINANCE BANK",
    code: "090421",
  },
  {
    id: 273,
    slug: "ibolo_micorfinance_bank_ltd",
    name: "Ibolo Micorfinance Bank Ltd",
    code: "090532",
  },
  {
    id: 274,
    slug: "ibom_fadama_microfinance_bank",
    name: "Ibom Fadama Microfinance Bank",
    code: "090519",
  },
  {
    id: 275,
    slug: "ibu_aje_microfinance",
    name: "Ibu-Aje Microfinance",
    code: "090488",
  },
  {
    id: 276,
    slug: "ijebu_ife_microfinance_bank_ltd",
    name: "Ijebu-Ife Microfinance Bank Ltd",
    code: "090546",
  },
  {
    id: 277,
    slug: "ikoyi_osun_microfinance_bank",
    name: "Ikoyi-Osun Microfinance Bank",
    code: "090536",
  },
  {
    id: 278,
    slug: "ilaro_poly_microfinance_bank_ltd",
    name: "Ilaro Poly Microfinance Bank Ltd",
    code: "090571",
  },
  {
    id: 279,
    slug: "iperu_microfinance_bank",
    name: "Iperu Microfinance Bank",
    code: "090493",
  },
  {
    id: 280,
    slug: "island_mfb",
    name: "Island MFB",
    code: "090584",
  },
  {
    id: 281,
    slug: "iwade_microfinance_bank_ltd",
    name: "Iwade Microfinance Bank Ltd",
    code: "090578",
  },
  {
    id: 282,
    slug: "iwoama_microfinance_bank",
    name: "Iwoama Microfinance Bank",
    code: "090543",
  },
  {
    id: 283,
    slug: "iyamoye_microfinance_bank_ltd",
    name: "Iyamoye Microfinance Bank Ltd",
    code: "090570",
  },
  {
    id: 284,
    slug: "iyin_ekiti_mfb",
    name: "Iyin Ekiti MFB",
    code: "090620",
  },
  {
    id: 285,
    slug: "jaiz_bank",
    name: "JAIZ BANK",
    code: "000006",
  },
  {
    id: 286,
    slug: "jessefield_microfinance_bank",
    name: "JESSEFIELD MICROFINANCE BANK",
    code: "090352",
  },
  {
    id: 287,
    slug: "jubilee_life",
    name: "JUBILEE LIFE",
    code: "090003",
  },
  {
    id: 288,
    slug: "kadpoly_microfinance_bank",
    name: "KADPOLY MICROFINANCE BANK",
    code: "090320",
  },
  {
    id: 289,
    slug: "kano_poly_mfb",
    name: "KANO POLY MFB",
    code: "090592",
  },
  {
    id: 290,
    slug: "kcmb_microfinance_bank",
    name: "KCMB MICROFINANCE BANK",
    code: "090191",
  },
  {
    id: 291,
    slug: "kegow",
    name: "KEGOW",
    code: "100015",
  },
  {
    id: 292,
    slug: "kegow_chamsmobile",
    name: "KEGOW(CHAMSMOBILE)",
    code: "100036",
  },
  {
    id: 293,
    slug: "kenechukwu_microfinance_bank",
    name: "KENECHUKWU MICROFINANCE BANK",
    code: "090602",
  },
  {
    id: 294,
    slug: "keystone_bank",
    name: "KEYSTONE BANK",
    code: "000002",
  },
  {
    id: 295,
    slug: "kku_microfinance_bank",
    name: "KKU Microfinance Bank",
    code: "090606",
  },
  {
    id: 296,
    slug: "kolomoni_microfinance_bank",
    name: "KOLOMONI MICROFINANCE BANK",
    code: "090480",
  },
  {
    id: 297,
    slug: "kongapay",
    name: "KONGAPAY",
    code: "100025",
  },
  {
    id: 298,
    slug: "kontagora_microfinance_bank",
    name: "KONTAGORA MICROFINANCE BANK",
    code: "090299",
  },
  {
    id: 299,
    slug: "kredi_money_microfinance_bank",
    name: "KREDI MONEY MICROFINANCE BANK ",
    code: "090380",
  },
  {
    id: 300,
    slug: "kuda_microfinance_bank",
    name: "KUDA MICROFINANCE BANK",
    code: "090267",
  },
  {
    id: 301,
    slug: "kayvee_microfinance_bank",
    name: "Kayvee Microfinance Bank",
    code: "090554",
  },
  {
    id: 302,
    slug: "kc_microfinance_bank",
    name: "Kc Microfinance Bank",
    code: "090549",
  },
  {
    id: 303,
    slug: "kingdom_college_microfinance_bank",
    name: "Kingdom College  Microfinance Bank",
    code: "090487",
  },
  {
    id: 304,
    slug: "kwasu_mf_bank",
    name: "Kwasu MF Bank",
    code: "090450",
  },
  {
    id: 305,
    slug: "lagos_building_and_investment_company",
    name: "LAGOS BUILDING AND INVESTMENT COMPANY",
    code: "070012",
  },
  {
    id: 306,
    slug: "landgold_microfinance_bank",
    name: "LANDGOLD  MICROFINANCE BANK",
    code: "090422",
  },
  {
    id: 307,
    slug: "lapo_microfinance_bank",
    name: "LAPO MICROFINANCE BANK",
    code: "090177",
  },
  {
    id: 308,
    slug: "lavender_microfinance_bank",
    name: "LAVENDER MICROFINANCE BANK",
    code: "090271",
  },
  {
    id: 309,
    slug: "legend_microfinance_bank",
    name: "LEGEND MICROFINANCE BANK",
    code: "090372",
  },
  {
    id: 310,
    slug: "letshego_mfb",
    name: "LETSHEGO MFB",
    code: "090420",
  },
  {
    id: 311,
    slug: "links_microfinance_bank",
    name: "LINKS MICROFINANCE BANK",
    code: "090435",
  },
  {
    id: 312,
    slug: "livingtrust_mortgage_bank_plc",
    name: "LIVINGTRUST MORTGAGE BANK PLC",
    code: "070007",
  },
  {
    id: 313,
    slug: "lotus_bank",
    name: "LOTUS BANK",
    code: "000029",
  },
  {
    id: 314,
    slug: "lovonus_microfinance_bank",
    name: "LOVONUS MICROFINANCE BANK",
    code: "090265",
  },
  {
    id: 315,
    slug: "lifegate_microfinance_bank_ltd",
    name: "Lifegate Microfinance Bank Ltd",
    code: "090557",
  },
  {
    id: 316,
    slug: "light_microfinance_bank",
    name: "Light Microfinance Bank",
    code: "090477",
  },
  {
    id: 317,
    slug: "lobrem_microfinance_bank",
    name: "Lobrem Microfinance Bank",
    code: "090537",
  },
  {
    id: 318,
    slug: "m36",
    name: "M36",
    code: "100035",
  },
  {
    id: 319,
    slug: "madobi_mfb",
    name: "MADOBI MFB",
    code: "090605",
  },
  {
    id: 320,
    slug: "mainland_microfinance_bank",
    name: "MAINLAND MICROFINANCE BANK",
    code: "090323",
  },
  {
    id: 321,
    slug: "mainstreet_microfinance_bank",
    name: "MAINSTREET MICROFINANCE BANK",
    code: "090171",
  },
  {
    id: 322,
    slug: "malachy_microfinance_bank",
    name: "MALACHY MICROFINANCE BANK",
    code: "090174",
  },
  {
    id: 323,
    slug: "manny_microfinance_bank",
    name: "MANNY MICROFINANCE BANK",
    code: "090383",
  },
  {
    id: 324,
    slug: "maritime_microfinance_bank",
    name: "MARITIME MICROFINANCE BANK",
    code: "090410",
  },
  {
    id: 325,
    slug: "mautech_microfinance_bank",
    name: "MAUTECH MICROFINANCE BANK",
    code: "090423",
  },
  {
    id: 326,
    slug: "mayfair_microfinance_bank",
    name: "MAYFAIR MICROFINANCE BANK",
    code: "090321",
  },
  {
    id: 327,
    slug: "mayfresh_mortgage_bank",
    name: "MAYFRESH MORTGAGE BANK",
    code: "070019",
  },
  {
    id: 328,
    slug: "megapraise_microfinance_bank",
    name: "MEGAPRAISE MICROFINANCE BANK",
    code: "090280",
  },
  {
    id: 329,
    slug: "memphis_microfinance_bank",
    name: "MEMPHIS MICROFINANCE BANK",
    code: "090432",
  },
  {
    id: 330,
    slug: "meridian_microfinance_bank",
    name: "MERIDIAN MICROFINANCE BANK",
    code: "090275",
  },
  {
    id: 331,
    slug: "michael_okpara_uniagric_microfinance_bank",
    name: "MICHAEL OKPARA UNIAGRIC MICROFINANCE BANK",
    code: "090659",
  },
  {
    id: 332,
    slug: "microcred_microfinance_bank",
    name: "MICROCRED MICROFINANCE BANK",
    code: "090136",
  },
  {
    id: 333,
    slug: "microvis_microfinance_bank",
    name: "MICROVIS MICROFINANCE BANK ",
    code: "090113",
  },
  {
    id: 334,
    slug: "midland_microfinance_bank",
    name: "MIDLAND MICROFINANCE BANK",
    code: "090192",
  },
  {
    id: 335,
    slug: "mint_finex_mfb",
    name: "MINT-FINEX MFB",
    code: "090281",
  },
  {
    id: 336,
    slug: "mkobo_microfinance_bank_ltd",
    name: "MKOBO MICROFINANCE BANK LTD",
    code: "090455",
  },
  {
    id: 337,
    slug: "molusi_microfinance_bank",
    name: "MOLUSI MICROFINANCE BANK",
    code: "090362",
  },
  {
    id: 338,
    slug: "momo_payment_service_bank",
    name: "MOMO PAYMENT SERVICE BANK ",
    code: "120003",
  },
  {
    id: 339,
    slug: "money_box",
    name: "MONEY BOX",
    code: "100020",
  },
  {
    id: 340,
    slug: "money_master_psb",
    name: "MONEY MASTER PSB",
    code: "120005",
  },
  {
    id: 341,
    slug: "money_trust_microfinance_bank",
    name: "MONEY TRUST MICROFINANCE BANK",
    code: "090129",
  },
  {
    id: 342,
    slug: "moniepoint_microfinance_bank",
    name: "MONIEPOINT MICROFINANCE BANK",
    code: "090405",
  },
  {
    id: 343,
    slug: "mozfin_microfinance_bank",
    name: "MOZFIN MICROFINANCE BANK",
    code: "090392",
  },
  {
    id: 344,
    slug: "mutual_benefits_microfinance_bank",
    name: "MUTUAL BENEFITS MICROFINANCE BANK",
    code: "090190",
  },
  {
    id: 345,
    slug: "mutual_trust_microfinance_bank",
    name: "MUTUAL TRUST MICROFINANCE BANK",
    code: "090151",
  },
  {
    id: 346,
    slug: "mab_allianz_mfb",
    name: "Mab Allianz MFB",
    code: "090623",
  },
  {
    id: 347,
    slug: "macrod_mfb",
    name: "Macrod MFB",
    code: "090603",
  },
  {
    id: 348,
    slug: "maintrust_microfinance_bank",
    name: "Maintrust Microfinance Bank",
    code: "090465",
  },
  {
    id: 349,
    slug: "medef_microfinance_bank",
    name: "Medef Microfinance Bank",
    code: "090612",
  },
  {
    id: 350,
    slug: "mercury_mfb",
    name: "Mercury MFB",
    code: "090589",
  },
  {
    id: 351,
    slug: "mgbidi_microfinance_bank",
    name: "Mgbidi Microfinance Bank",
    code: "090528",
  },
  {
    id: 352,
    slug: "microbiz_microfinance_bank",
    name: "Microbiz Microfinance Bank",
    code: "090587",
  },
  {
    id: 353,
    slug: "monarch_microfinance_bank",
    name: "Monarch Microfinance Bank",
    code: "090462",
  },
  {
    id: 354,
    slug: "moyofade_mf_bank",
    name: "Moyofade MF Bank",
    code: "090448",
  },
  {
    id: 355,
    slug: "nagarta_microfinance_bank",
    name: "NAGARTA MICROFINANCE BANK",
    code: "090152",
  },
  {
    id: 356,
    slug: "nasarawa_microfinance_bank",
    name: "NASARAWA MICROFINANCE BANK",
    code: "090349",
  },
  {
    id: 357,
    slug: "ndiorah_microfinance_bank",
    name: "NDIORAH MICROFINANCE BANK",
    code: "090128",
  },
  {
    id: 358,
    slug: "neptune_microfinance_bank",
    name: "NEPTUNE MICROFINANCE BANK",
    code: "090329",
  },
  {
    id: 359,
    slug: "new_dawn_microfinance_bank",
    name: "NEW DAWN MICROFINANCE BANK",
    code: "090205",
  },
  {
    id: 360,
    slug: "new_golden_pastures_microfinance_bank",
    name: "NEW GOLDEN PASTURES MICROFINANCE BANK",
    code: "090378",
  },
  {
    id: 361,
    slug: "new_prudential_bank",
    name: "NEW PRUDENTIAL BANK",
    code: "090108",
  },
  {
    id: 362,
    slug: "newedge_finance_ltd",
    name: "NEWEDGE FINANCE LTD",
    code: "050004",
  },
  {
    id: 363,
    slug: "nigerian_navy_microfinance_bank",
    name: "NIGERIAN NAVY MICROFINANCE BANK ",
    code: "090263",
  },
  {
    id: 364,
    slug: "nip_virtual_bank",
    name: "NIP VIRTUAL BANK",
    code: "999999",
  },
  {
    id: 365,
    slug: "nirsal_national_microfinance_bank",
    name: "NIRSAL NATIONAL MICROFINANCE BANK",
    code: "090194",
  },
  {
    id: 366,
    slug: "nnew_women_microfinance_bank",
    name: "NNEW WOMEN MICROFINANCE BANK ",
    code: "090283",
  },
  {
    id: 367,
    slug: "nova_merchant_bank",
    name: "NOVA MERCHANT BANK",
    code: "060003",
  },
  {
    id: 368,
    slug: "nownow_digital_systems_limited",
    name: "NOWNOW DIGITAL SYSTEMS LIMITED",
    code: "100032",
  },
  {
    id: 369,
    slug: "npf_microfinance_bank",
    name: "NPF MICROFINANCE BANK",
    code: "070001",
  },
  {
    id: 370,
    slug: "nuggets_mfb",
    name: "NUGGETS MFB",
    code: "090676",
  },
  {
    id: 371,
    slug: "nuture_microfinance_bank",
    name: "NUTURE MICROFINANCE BANK",
    code: "090364",
  },
  {
    id: 372,
    slug: "nwannegadi_microfinance_bank",
    name: "NWANNEGADI MICROFINANCE BANK",
    code: "090399",
  },
  {
    id: 373,
    slug: "nice_microfinance_bank",
    name: "Nice Microfinance Bank",
    code: "090459",
  },
  {
    id: 374,
    slug: "nigeria_prisons_microfinance_bank",
    name: "Nigeria Prisons Microfinance Bank",
    code: "090505",
  },
  {
    id: 375,
    slug: "nkpolu_ust_microfinance",
    name: "Nkpolu-Ust Microfinance",
    code: "090535",
  },
  {
    id: 376,
    slug: "nsuk_microfinance_bank",
    name: "Nsuk  Microfinance Bank",
    code: "090491",
  },
  {
    id: 377,
    slug: "numo_microfinance_bank",
    name: "Numo Microfinance Bank",
    code: "090516",
  },
  {
    id: 378,
    slug: "oakland_microfinance_bank",
    name: "OAKLAND MICROFINANCE BANK",
    code: "090437",
  },
  {
    id: 379,
    slug: "oau_microfinance_bank_ltd",
    name: "OAU MICROFINANCE BANK LTD",
    code: "090345",
  },
  {
    id: 380,
    slug: "oche_microfinance_bank",
    name: "OCHE MICROFINANCE BANK",
    code: "090333",
  },
  {
    id: 381,
    slug: "ohafia_microfinance_bank",
    name: "OHAFIA MICROFINANCE BANK",
    code: "090119",
  },
  {
    id: 382,
    slug: "okpoga_microfinance_bank",
    name: "OKPOGA MICROFINANCE BANK",
    code: "090161",
  },
  {
    id: 383,
    slug: "olabisi_onabanjo_university_microfinance",
    name: "OLABISI ONABANJO UNIVERSITY MICROFINANCE ",
    code: "090272",
  },
  {
    id: 384,
    slug: "olowolagba_microfinance_bank",
    name: "OLOWOLAGBA MICROFINANCE BANK",
    code: "090404",
  },
  {
    id: 385,
    slug: "omak_microfinance_bank",
    name: "OMAK MICROFINANCE BANK",
    code: "090700",
  },
  {
    id: 386,
    slug: "omiye_microfinance_bank",
    name: "OMIYE MICROFINANCE BANK",
    code: "090295",
  },
  {
    id: 387,
    slug: "opay",
    name: "OPAY",
    code: "100004",
  },
  {
    id: 388,
    slug: "optimus_bank",
    name: "OPTIMUS BANK",
    code: "000036",
  },
  {
    id: 389,
    slug: "oscotech_microfinance_bank",
    name: "OSCOTECH MICROFINANCE BANK",
    code: "090396",
  },
  {
    id: 390,
    slug: "octopus_microfinance_bank_ltd",
    name: "Octopus Microfinance Bank Ltd",
    code: "090576",
  },
  {
    id: 391,
    slug: "ojokoro_microfinance_bank",
    name: "Ojokoro Microfinance Bank",
    code: "090527",
  },
  {
    id: 392,
    slug: "oke_aro_oredegbe_microfinance_bank_ltd",
    name: "Oke-Aro Oredegbe Microfinance Bank Ltd",
    code: "090565",
  },
  {
    id: 393,
    slug: "okuku_microfinance_bank_ltd",
    name: "Okuku Microfinance Bank Ltd",
    code: "090566",
  },
  {
    id: 394,
    slug: "olofin_owena_microfinance_bank",
    name: "Olofin Owena Microfinance Bank",
    code: "090468",
  },
  {
    id: 395,
    slug: "oluchukwu_microfinance_bank",
    name: "Oluchukwu Microfinance Bank",
    code: "090471",
  },
  {
    id: 396,
    slug: "oluyole_microfinance_bank",
    name: "Oluyole Microfinance Bank",
    code: "090460",
  },
  {
    id: 397,
    slug: "oraukwu_microfinance_bank",
    name: "Oraukwu  Microfinance Bank",
    code: "090492",
  },
  {
    id: 398,
    slug: "orisun_mfb",
    name: "Orisun MFB",
    code: "090588",
  },
  {
    id: 399,
    slug: "orokam_microfinance_bank_ltd",
    name: "Orokam Microfinance Bank Ltd",
    code: "090567",
  },
  {
    id: 400,
    slug: "ospoly_microfinance_bank",
    name: "Ospoly Microfinance Bank",
    code: "090456",
  },
  {
    id: 401,
    slug: "otech_microfinance_bank_ltd",
    name: "Otech Microfinance Bank Ltd",
    code: "090580",
  },
  {
    id: 402,
    slug: "otuo_microfinance_bank_ltd",
    name: "Otuo Microfinance Bank Ltd",
    code: "090542",
  },
  {
    id: 403,
    slug: "paga",
    name: "PAGA",
    code: "100002",
  },
  {
    id: 404,
    slug: "page_mfbank",
    name: "PAGE MFBANK",
    code: "070008",
  },
  {
    id: 405,
    slug: "palmpay",
    name: "PALMPAY",
    code: "100033",
  },
  {
    id: 406,
    slug: "parallex_bank",
    name: "PARALLEX BANK",
    code: "000030",
  },
  {
    id: 407,
    slug: "parkway_mf_bank",
    name: "PARKWAY MF BANK",
    code: "090390",
  },
  {
    id: 408,
    slug: "parkway_readycash",
    name: "PARKWAY-READYCASH",
    code: "100003",
  },
  {
    id: 409,
    slug: "parralex_microfinance_bank",
    name: "PARRALEX MICROFINANCE BANK",
    code: "090004",
  },
  {
    id: 410,
    slug: "patrickgold_microfinance_bank",
    name: "PATRICKGOLD MICROFINANCE BANK",
    code: "090317",
  },
  {
    id: 411,
    slug: "paystack_titan",
    name: "PAYSTACK-TITAN",
    code: "100039",
  },
  {
    id: 412,
    slug: "peace_microfinance_bank",
    name: "PEACE MICROFINANCE BANK",
    code: "090402",
  },
  {
    id: 413,
    slug: "pecantrust_microfinance_bank",
    name: "PECANTRUST MICROFINANCE BANK",
    code: "090137",
  },
  {
    id: 414,
    slug: "peniel_micorfinance_bank_ltd",
    name: "PENIEL MICORFINANCE BANK LTD",
    code: "090379",
  },
  {
    id: 415,
    slug: "pennywise_microfinance_bank",
    name: "PENNYWISE MICROFINANCE BANK ",
    code: "090196",
  },
  {
    id: 416,
    slug: "personal_trust_microfinance_bank",
    name: "PERSONAL TRUST MICROFINANCE BANK",
    code: "090135",
  },
  {
    id: 417,
    slug: "petra_microfinance_bank",
    name: "PETRA MICROFINANCE BANK",
    code: "090165",
  },
  {
    id: 418,
    slug: "pillar_microfinance_bank",
    name: "PILLAR MICROFINANCE BANK",
    code: "090289",
  },
  {
    id: 419,
    slug: "platinum_mortgage_bank",
    name: "PLATINUM MORTGAGE BANK",
    code: "070013",
  },
  {
    id: 420,
    slug: "polaris_bank",
    name: "POLARIS BANK",
    code: "000008",
  },
  {
    id: 421,
    slug: "polyunwana_microfinance_bank",
    name: "POLYUNWANA MICROFINANCE BANK",
    code: "090296",
  },
  {
    id: 422,
    slug: "preeminent_microfinance_bank",
    name: "PREEMINENT MICROFINANCE BANK",
    code: "090412",
  },
  {
    id: 423,
    slug: "premium_trust_bank",
    name: "PREMIUM TRUST  BANK",
    code: "000031",
  },
  {
    id: 424,
    slug: "prestige_microfinance_bank",
    name: "PRESTIGE MICROFINANCE BANK",
    code: "090274",
  },
  {
    id: 425,
    slug: "providus_bank",
    name: "PROVIDUS BANK",
    code: "000023",
  },
  {
    id: 426,
    slug: "purplemoney_microfinance_bank",
    name: "PURPLEMONEY MICROFINANCE BANK",
    code: "090303",
  },
  {
    id: 427,
    slug: "pyramid_microfinance_bank",
    name: "PYRAMID MICROFINANCE BANK",
    code: "090657",
  },
  {
    id: 428,
    slug: "palmcoast_microfinance_bank",
    name: "Palmcoast Microfinance Bank",
    code: "090497",
  },
  {
    id: 429,
    slug: "polyibadan_microfinance_bank",
    name: "PolyIbadan Microfinance Bank",
    code: "090534",
  },
  {
    id: 430,
    slug: "prisco_microfinance_bank",
    name: "Prisco  Microfinance Bank",
    code: "090481",
  },
  {
    id: 431,
    slug: "pristine_divitis_microfinance_bank",
    name: "Pristine Divitis Microfinance Bank",
    code: "090499",
  },
  {
    id: 432,
    slug: "projects_microfinance_bank",
    name: "Projects Microfinance Bank",
    code: "090503",
  },
  {
    id: 433,
    slug: "prospa_capital_microfinance_bank",
    name: "Prospa Capital MICROFINANCE BANK",
    code: "090495",
  },
  {
    id: 434,
    slug: "quickfund_microfinance_bank",
    name: "QUICKFUND MICROFINANCE BANK",
    code: "090261",
  },
  {
    id: 435,
    slug: "qube_microfinance_bank_ltd",
    name: "Qube Microfinance Bank Ltd",
    code: "090569",
  },
  {
    id: 436,
    slug: "rahama_microfinance_bank",
    name: "RAHAMA MICROFINANCE BANK",
    code: "090170",
  },
  {
    id: 437,
    slug: "rand_merchant_bank",
    name: "RAND MERCHANT BANK",
    code: "000024",
  },
  {
    id: 438,
    slug: "rayyan_microfinance_bank",
    name: "RAYYAN Microfinance Bank",
    code: "090616",
  },
  {
    id: 439,
    slug: "refuge_mortgage_bank",
    name: "REFUGE MORTGAGE BANK",
    code: "070011",
  },
  {
    id: 440,
    slug: "regent_microfinance_bank",
    name: "REGENT MICROFINANCE BANK",
    code: "090125",
  },
  {
    id: 441,
    slug: "reliance_microfinance_bank",
    name: "RELIANCE MICROFINANCE BANK",
    code: "090173",
  },
  {
    id: 442,
    slug: "renmoney_microfinance_bank",
    name: "RENMONEY MICROFINANCE BANK ",
    code: "090198",
  },
  {
    id: 443,
    slug: "rephidim_microfinance_bank",
    name: "REPHIDIM MICROFINANCE BANK",
    code: "090322",
  },
  {
    id: 444,
    slug: "rex_microfinance_bank",
    name: "REX  Microfinance Bank",
    code: "090449",
  },
  {
    id: 445,
    slug: "richway_microfinance_bank",
    name: "RICHWAY MICROFINANCE BANK",
    code: "090132",
  },
  {
    id: 446,
    slug: "rigo_microfinance_bank",
    name: "RIGO MICROFINANCE BANK",
    code: "090433",
  },
  {
    id: 447,
    slug: "rima_microfinance_bank",
    name: "RIMA MICROFINANCE BANK",
    code: "090443",
  },
  {
    id: 448,
    slug: "royal_exchange_microfinance_bank",
    name: "ROYAL EXCHANGE MICROFINANCE BANK",
    code: "090138",
  },
  {
    id: 449,
    slug: "rubies_microfinance_bank",
    name: "RUBIES MICROFINANCE BANK",
    code: "090175",
  },
  {
    id: 450,
    slug: "radalpha_microfinance_bank",
    name: "Radalpha Microfinance Bank",
    code: "090496",
  },
  {
    id: 451,
    slug: "rehoboth_microfinance_bank",
    name: "Rehoboth Microfinance Bank",
    code: "090463",
  },
  {
    id: 452,
    slug: "rima_growth_pathway_microfinance_bank",
    name: "Rima Growth Pathway Microfinance Bank ",
    code: "090515",
  },
  {
    id: 453,
    slug: "rockshield_microfinance_bank",
    name: "Rockshield Microfinance Bank",
    code: "090547",
  },
  {
    id: 454,
    slug: "safe_haven_microfinance_bank",
    name: "SAFE HAVEN MICROFINANCE BANK",
    code: "090286",
  },
  {
    id: 455,
    slug: "safegate_microfinance_bank",
    name: "SAFEGATE MICROFINANCE BANK",
    code: "090485",
  },
  {
    id: 456,
    slug: "safetrust",
    name: "SAFETRUST",
    code: "090006",
  },
  {
    id: 457,
    slug: "sagamu_microfinance_bank",
    name: "SAGAMU MICROFINANCE BANK",
    code: "090140",
  },
  {
    id: 458,
    slug: "sagegrey_finance_limited",
    name: "SAGEGREY FINANCE LIMITED",
    code: "050003",
  },
  {
    id: 459,
    slug: "seed_capital_microfinance_bank",
    name: "SEED CAPITAL MICROFINANCE BANK",
    code: "090112",
  },
  {
    id: 460,
    slug: "seedvest_microfinance_bank",
    name: "SEEDVEST MICROFINANCE BANK",
    code: "090369",
  },
  {
    id: 461,
    slug: "sherperd_trust_microfinance_bank",
    name: "SHERPERD TRUST MICROFINANCE BANK",
    code: "090401",
  },
  {
    id: 462,
    slug: "signature_bank",
    name: "SIGNATURE BANK",
    code: "000034",
  },
  {
    id: 463,
    slug: "simple_finance_limited",
    name: "SIMPLE FINANCE LIMITED",
    code: "050008",
  },
  {
    id: 464,
    slug: "smartcash_payment_service_bank",
    name: "SMARTCASH PAYMENT SERVICE BANK",
    code: "120004",
  },
  {
    id: 465,
    slug: "solid_allianze_microfinance_bank",
    name: "SOLID ALLIANZE MICROFINANCE BANK",
    code: "090506",
  },
  {
    id: 466,
    slug: "sparkle",
    name: "SPARKLE",
    code: "090325",
  },
  {
    id: 467,
    slug: "spectrum_microfinance_bank",
    name: "SPECTRUM MICROFINANCE BANK ",
    code: "090436",
  },
  {
    id: 468,
    slug: "stanbic_ibtc_ease_wallet",
    name: "STANBIC IBTC @EASE WALLET",
    code: "100007",
  },
  {
    id: 469,
    slug: "stanbic_ibtc_bank",
    name: "STANBIC IBTC BANK",
    code: "000012",
  },
  {
    id: 470,
    slug: "standard_chartered_bank",
    name: "STANDARD CHARTERED BANK",
    code: "000021",
  },
  {
    id: 471,
    slug: "standard_microfinance_bank",
    name: "STANDARD MICROFINANCE BANK",
    code: "090182",
  },
  {
    id: 472,
    slug: "stanford_microfinance_bank",
    name: "STANFORD MICROFINANCE BANK",
    code: "090162",
  },
  {
    id: 473,
    slug: "stateside_mfb",
    name: "STATESIDE MFB",
    code: "090583",
  },
  {
    id: 474,
    slug: "stb_mortgage_bank",
    name: "STB MORTGAGE BANK",
    code: "070022",
  },
  {
    id: 475,
    slug: "stellas_microfinance_bank",
    name: "STELLAS MICROFINANCE BANK ",
    code: "090262",
  },
  {
    id: 476,
    slug: "sterling_bank",
    name: "STERLING BANK",
    code: "000001",
  },
  {
    id: 477,
    slug: "sterling_mobile",
    name: "STERLING MOBILE",
    code: "100022",
  },
  {
    id: 478,
    slug: "stockcorp_microfinance_bank",
    name: "STOCKCORP  MICROFINANCE BANK",
    code: "090340",
  },
  {
    id: 479,
    slug: "sulspap_microfinance_bank",
    name: "SULSPAP MICROFINANCE BANK",
    code: "090305",
  },
  {
    id: 480,
    slug: "sunbeam_microfinance_bank",
    name: "SUNBEAM MICROFINANCE BANK",
    code: "090302",
  },
  {
    id: 481,
    slug: "suntrust_bank",
    name: "SUNTRUST BANK",
    code: "000022",
  },
  {
    id: 482,
    slug: "support_microfinance_bank",
    name: "SUPPORT MICROFINANCE BANK",
    code: "090446",
  },
  {
    id: 483,
    slug: "seap_microfinance_bank",
    name: "Seap Microfinance Bank",
    code: "090513",
  },
  {
    id: 484,
    slug: "shalom_microfinance_bank",
    name: "Shalom Microfinance Bank",
    code: "090502",
  },
  {
    id: 485,
    slug: "shield_microfinance_bank_ltd",
    name: "Shield Microfinance Bank Ltd",
    code: "090559",
  },
  {
    id: 486,
    slug: "shongom_microfinance_bank_ltd",
    name: "Shongom Microfinance Bank Ltd",
    code: "090558",
  },
  {
    id: 487,
    slug: "snow_microfinance_bank",
    name: "Snow Microfinance Bank",
    code: "090573",
  },
  {
    id: 488,
    slug: "solidrock_microfinance_bank",
    name: "Solidrock Microfinance Bank",
    code: "090524",
  },
  {
    id: 489,
    slug: "supreme_microfinance_bank_ltd",
    name: "Supreme Microfinance Bank Ltd",
    code: "090564",
  },
  {
    id: 490,
    slug: "tagpay",
    name: "TAGPAY",
    code: "100023",
  },
  {
    id: 491,
    slug: "taj_bank",
    name: "TAJ BANK",
    code: "000026",
  },
  {
    id: 492,
    slug: "tajwallet",
    name: "TAJWALLET",
    code: "080002",
  },
  {
    id: 493,
    slug: "tanadi_mfb_crust",
    name: "TANADI MFB (CRUST)",
    code: "090560",
  },
  {
    id: 494,
    slug: "tangerine_money",
    name: "TANGERINE MONEY",
    code: "090426",
  },
  {
    id: 495,
    slug: "tasued_microfinance_bank_ltd",
    name: "TASUED MICROFINANCE BANK LTD",
    code: "090593",
  },
  {
    id: 496,
    slug: "teasy_mobile",
    name: "TEASY MOBILE",
    code: "100010",
  },
  {
    id: 497,
    slug: "tekla_finance_ltd",
    name: "TEKLA FINANCE LTD",
    code: "050007",
  },
  {
    id: 498,
    slug: "tenn_microfinance_bank",
    name: "TENN MICROFINANCE BANK",
    code: "090716",
  },
  {
    id: 499,
    slug: "the_millennium_microfinance_bank",
    name: "THE MILLENNIUM MICROFINANCE BANK",
    code: "090711",
  },
  {
    id: 500,
    slug: "think_finance_microfinance_bank",
    name: "THINK FINANCE MICROFINANCE BANK",
    code: "090373",
  },
  {
    id: 501,
    slug: "titan_trust_bank",
    name: "TITAN TRUST BANK",
    code: "000025",
  },
  {
    id: 502,
    slug: "tofa_microfinance_bank",
    name: "TOFA MICROFINANCE BANK",
    code: "090714",
  },
  {
    id: 503,
    slug: "trident_microfinance_bank",
    name: "TRIDENT MICROFINANCE BANK",
    code: "090146",
  },
  {
    id: 504,
    slug: "trinity_financial_services_limited",
    name: "TRINITY FINANCIAL SERVICES LIMITED",
    code: "050014",
  },
  {
    id: 505,
    slug: "trust_microfinance_bank",
    name: "TRUST MICROFINANCE BANK",
    code: "090327",
  },
  {
    id: 506,
    slug: "trustbanc_j6_microfinance_bank_limited",
    name: "TRUSTBANC J6 MICROFINANCE BANK LIMITED",
    code: "090123",
  },
  {
    id: 507,
    slug: "trustbond_mortgage_bank",
    name: "TRUSTBOND MORTGAGE BANK",
    code: "090005",
  },
  {
    id: 508,
    slug: "trustfund_microfinance_bank",
    name: "TRUSTFUND MICROFINANCE BANK ",
    code: "090276",
  },
  {
    id: 509,
    slug: "total_trust_microfinance_bank",
    name: "Total Trust Microfinance Bank",
    code: "090613",
  },
  {
    id: 510,
    slug: "transpay_microfinance_bank",
    name: "TransPay MICROFINANCE BANK ",
    code: "090708",
  },
  {
    id: 511,
    slug: "triple_a_microfinance_bank",
    name: "Triple A Microfinance Bank",
    code: "090525",
  },
  {
    id: 512,
    slug: "u_c_microfinance_bank",
    name: "U & C MICROFINANCE BANK",
    code: "090315",
  },
  {
    id: 513,
    slug: "uba_moni",
    name: "UBA MONI",
    code: "000040",
  },
  {
    id: 514,
    slug: "ucee_daily_trust_microfinance_bank",
    name: "UCEE/DAILY TRUST MICROFINANCE BANK ",
    code: "090706",
  },
  {
    id: 515,
    slug: "uda_microfinance_bank",
    name: "UDA MICROFINANCE BANK",
    code: "090403",
  },
  {
    id: 516,
    slug: "unaab_microfinance_bank",
    name: "UNAAB MICROFINANCE BANK",
    code: "090331",
  },
  {
    id: 517,
    slug: "uniben_microfinance_bank",
    name: "UNIBEN MICROFINANCE BANK",
    code: "090266",
  },
  {
    id: 518,
    slug: "unical_microfinance_bank",
    name: "UNICAL MICROFINANCE BANK",
    code: "090193",
  },
  {
    id: 519,
    slug: "unilag_microfinance_bank",
    name: "UNILAG  Microfinance Bank",
    code: "090452",
  },
  {
    id: 520,
    slug: "unilorin_microfinance_bank",
    name: "UNILORIN MICROFINANCE BANK",
    code: "090341",
  },
  {
    id: 521,
    slug: "unimaid_microfinance_bank",
    name: "UNIMAID MICROFINANCE BANK",
    code: "090464",
  },
  {
    id: 522,
    slug: "union_bank",
    name: "UNION BANK",
    code: "000018",
  },
  {
    id: 523,
    slug: "united_bank_for_africa",
    name: "UNITED BANK FOR AFRICA",
    code: "000004",
  },
  {
    id: 524,
    slug: "unity_bank",
    name: "UNITY BANK",
    code: "000011",
  },
  {
    id: 525,
    slug: "uniuyo_microfinance_bank",
    name: "UNIUYO MICROFINANCE BANK",
    code: "090338",
  },
  {
    id: 526,
    slug: "university_of_nigeria_nsukka_microfinance_bank",
    name: "UNIVERSITY OF NIGERIA, NSUKKA MICROFINANCE BANK",
    code: "090251",
  },
  {
    id: 527,
    slug: "uhuru_microfinance_bank",
    name: "Uhuru Microfinance Bank",
    code: "090517",
  },
  {
    id: 528,
    slug: "ummah_microfinance_bank",
    name: "Ummah Microfinance Bank ",
    code: "090609",
  },
  {
    id: 529,
    slug: "umuchinemere_procredit_microfinance_bank",
    name: "Umuchinemere Procredit Microfinance Bank",
    code: "090514",
  },
  {
    id: 530,
    slug: "umunnachi_microfinance_bank",
    name: "Umunnachi Microfinance Bank",
    code: "090510",
  },
  {
    id: 531,
    slug: "uniibadan_microfinance_bank",
    name: "Uniibadan Microfinance Bank",
    code: "090461",
  },
  {
    id: 532,
    slug: "uzondu_mf_bank",
    name: "Uzondu MF Bank",
    code: "090453",
  },
  {
    id: 533,
    slug: "vale_finance_limited",
    name: "VALE FINANCE LIMITED",
    code: "050020",
  },
  {
    id: 534,
    slug: "vfd_mfb",
    name: "VFD MFB",
    code: "090110",
  },
  {
    id: 535,
    slug: "virtue_microfinance_bank",
    name: "VIRTUE MICROFINANCE BANK",
    code: "090150",
  },
  {
    id: 536,
    slug: "visa_microfinance_bank",
    name: "VISA MICROFINANCE BANK",
    code: "090139",
  },
  {
    id: 537,
    slug: "vt_networks",
    name: "VT NETWORKS",
    code: "100012",
  },
  {
    id: 538,
    slug: "verdant_microfinance_bank",
    name: "Verdant Microfinance Bank",
    code: "090474",
  },
  {
    id: 539,
    slug: "waya_microfinance_bank_ltd",
    name: "WAYA MICROFINANCE BANK LTD",
    code: "090590",
  },
  {
    id: 540,
    slug: "wema_bank",
    name: "WEMA BANK",
    code: "000017",
  },
  {
    id: 541,
    slug: "wetland_microfinance_bank",
    name: "WETLAND  MICROFINANCE BANK",
    code: "090120",
  },
  {
    id: 542,
    slug: "winview_bank",
    name: "WINVIEW BANK",
    code: "090419",
  },
  {
    id: 543,
    slug: "wra_microfinance_bank",
    name: "WRA MICROFINANCE BANK",
    code: "090631",
  },
  {
    id: 544,
    slug: "xpress_payments",
    name: "XPRESS PAYMENTS",
    code: "090201",
  },
  {
    id: 545,
    slug: "xpress_wallet",
    name: "XPRESS WALLET",
    code: "100040",
  },
  {
    id: 546,
    slug: "xslnce_microfinance_bank",
    name: "XSLNCE MICROFINANCE BANK",
    code: "090124",
  },
  {
    id: 547,
    slug: "yct_microfinance_bank",
    name: "YCT MICROFINANCE BANK",
    code: "090466",
  },
  {
    id: 548,
    slug: "yes_microfinance_bank",
    name: "YES MICROFINANCE BANK",
    code: "090142",
  },
  {
    id: 549,
    slug: "yobe_microfinance_bank",
    name: "YOBE MICROFINANCE  BANK",
    code: "090252",
  },
  {
    id: 550,
    slug: "zedvance_finance_limited",
    name: "ZEDVANCE FINANCE LIMITED",
    code: "050019",
  },
  {
    id: 551,
    slug: "zenith_bank",
    name: "ZENITH BANK",
    code: "000015",
  },
  {
    id: 552,
    slug: "zenith_easy_wallet",
    name: "ZENITH EASY WALLET",
    code: "100034",
  },
  {
    id: 553,
    slug: "zenith_mobile",
    name: "ZENITH MOBILE",
    code: "100018",
  },
  {
    id: 554,
    slug: "zikora_microfinance_bank",
    name: "ZIKORA MICROFINANCE BANK",
    code: "090504",
  },
];
