import { Bank } from "@/src/types";

export const WEIGHTED_NIGERIAN_BANKS: Bank[] = [
  {
    id: 1,
    slug: "access_bank",
    name: "ACCESS BANK",
    code: "000014",
    oldCode: "044",
    weight: 1,
  },
  {
    id: 2,
    slug: "access_diamond_bank",
    name: "ACCESS(DIAMOND) BANK",
    code: "000014",
    oldCode: "063",
    weight: 1,
  },
  {
    id: 3,
    slug: "citi_bank",
    name: "CITI BANK",
    code: "000009",
    oldCode: "023",
    weight: 1,
  },
  {
    id: 4,
    slug: "ecobank",
    name: "ECOBANK NIGERIA",
    code: "000010",
    oldCode: "050",
    weight: 1,
  },
  {
    id: 5,
    slug: "enterprise_bank",
    name: "ENTERPRISE BANK",
    code: "000019",
    oldCode: "084",
    weight: 1,
  },
  {
    id: 6,
    slug: "fidelity_bank",
    name: "FIDELITY BANK",
    code: "000007",
    oldCode: "070",
    weight: 1,
  },
  {
    id: 7,
    slug: "first_bank_of_nigeria",
    name: "FIRST BANK OF NIGERIA",
    code: "000016",
    oldCode: "011",
    weight: 1,
  },
  {
    id: 8,
    slug: "first_city_monument_bank",
    name: "FIRST CITY MONUMENT BANK",
    code: "000003",
    oldCode: "214",
    weight: 1,
  },
  {
    id: 9,
    slug: "globus_bank",
    name: "GLOBUS BANK",
    code: "000027",
    oldCode: "103",
    weight: 1,
  },
  {
    id: 10,
    slug: "guarantee_trust_bank",
    name: "GUARANTY TRUST BANK",
    code: "000013",
    oldCode: "058",
    weight: 1,
  },
  {
    id: 11,
    slug: "heritage_bank",
    name: "HERITAGE BANK",
    code: "000020",
    oldCode: "030",
    weight: 1,
  },
  {
    id: 12,
    slug: "jaiz_bank",
    name: "JAIZ BANK",
    code: "000006",
    oldCode: "301",
    weight: 1,
  },
  {
    id: 13,
    slug: "keystone_bank",
    name: "KEYSTONE BANK",
    code: "000002",
    oldCode: "082",
    weight: 1,
  },
  {
    id: 14,
    slug: "lotus_bank",
    name: "LOTUS BANK",
    code: "000029",
    oldCode: "303",
    weight: 1,
  },
  {
    id: 15,
    slug: "mainstreet_microfinance_bank",
    name: "MAINSTREET MICROFINANCE BANK",
    code: "090171",
    oldCode: "014",
    weight: 1,
  },
  {
    id: 16,
    slug: "optimus_bank",
    name: "OPTIMUS BANK",
    code: "000036",
    oldCode: "106",
    weight: 1,
  },
  {
    id: 17,
    slug: "parallex_bank",
    name: "PARALLEX BANK",
    code: "000030",
    oldCode: "104",
    weight: 1,
  },
  {
    id: 18,
    slug: "polaris_bank",
    name: "POLARIS BANK",
    code: "000008",
    oldCode: "076",
    weight: 1,
  },
  {
    id: 19,
    slug: "premium_trust_bank",
    name: "PREMIUM TRUST  BANK",
    code: "000031",
    oldCode: "105",
    weight: 1,
  },
  {
    id: 20,
    slug: "providus_bank",
    name: "PROVIDUS BANK",
    code: "000023",
    oldCode: "101",
    weight: 1,
  },
  {
    id: 21,
    slug: "signature_bank",
    name: "SIGNATURE BANK",
    code: "000034",
    oldCode: "106",
    weight: 1,
  },
  {
    id: 22,
    slug: "stanbic_ibtc_bank",
    name: "STANBIC IBTC BANK",
    code: "000012",
    oldCode: "221",
    weight: 1,
  },
  {
    id: 23,
    slug: "standard_chartered_bank",
    name: "STANDARD CHARTERED BANK",
    code: "000021",
    oldCode: "068",
    weight: 1,
  },
  {
    id: 24,
    slug: "sterling_bank",
    name: "STERLING BANK",
    code: "000001",
    oldCode: "232",
    weight: 1,
  },
  {
    id: 25,
    slug: "suntrust_bank",
    name: "SUNTRUST",
    code: "000022",
    oldCode: "100",
    weight: 1,
  },
  {
    id: 26,
    slug: "titan_trust_bank",
    name: "TITAN TRUST BANK",
    code: "000025",
    oldCode: "102",
    weight: 1,
  },
  {
    id: 27,
    slug: "union_bank",
    name: "UNION BANK",
    code: "000018",
    oldCode: "032",
    weight: 1,
  },
  {
    id: 28,
    slug: "united_bank_for_africa",
    name: "UNITED BANK FOR AFRICA",
    code: "000004",
    oldCode: "033",
    weight: 1,
  },
  {
    id: 29,
    slug: "unity_bank",
    name: "UNITY BANK",
    code: "000011",
    oldCode: "215",
    weight: 1,
  },
  {
    id: 30,
    slug: "wema_bank",
    name: "WEMA BANK",
    code: "000017",
    oldCode: "035",
    weight: 1,
  },
  {
    id: 31,
    slug: "zenith_bank",
    name: "ZENITH BANK",
    code: "000015",
    oldCode: "057",
    weight: 1,
  },
];
